const data = [
  {
    id: "1",
    fname: "علیرضا",
    lname: "صابری",
    expert: "اورولوژی",
    university: "استنفورد",
    imgUrl: "544345.jpeg",
    rate: "4.6",
    address: "شهرک شریعتی",
    date: ["پنجشنبه", "سه شنبه", "دوشنبه"],
  },
  {
    id: "2",
    fname: "محمد",
    lname: "رضایی",
    expert: "گوش و حلق و بینی",
    university: "تبریز",
    imgUrl: "156921.jpeg",
    rate: "4.0",
    address: "پاسداران",
    date: ["سه شنبه", "شنبه"],
  },
  {
    id: "3",
    fname: "علی",
    lname: "نوروزی",
    expert: "داخلی",
    university: "هاروارد",
    imgUrl: "643966.jpeg",
    rate: "4.8",
    address: "تهرانپارس - فرجام",
    date: ["چهارشنبه", "سه شنبه", "شنبه"],
  },
  {
    id: "4",
    fname: "احمد",
    lname: "قادری",
    expert: "بیماری های عفونی",
    university: "علوم پزشکی ایران",
    imgUrl: "574387.jpeg",
    rate: "4.4",
    address: "امیرآباد شمالی",
    date: ["پنج شنبه", "یکشنبه"],
  },
  {
    id: "5",
    fname: "شهرام",
    lname: "کاظمی",
    expert: "اعصاب و روان",
    university: "شهید بهشتی",
    imgUrl: "455837.jpeg",
    rate: "4.2",
    address: "میدان ونک",
    date: ["سه شنبه", "دوشنبه", "شنبه"],
  },
  {
    id: "6",
    fname: "محمود",
    lname: "علوی",
    expert: "قلب و عروق",
    university: "تهران",
    imgUrl: "169469.jpeg",
    rate: "4.1",
    address: "آزادی - شادمان",
    date: ["سه شنبه", "شنبه"],
  },
  {
    id: "7",
    fname: "سمیه",
    lname: "شیری",
    expert: "اعصاب و روان",
    university: "شهید بهشتی",
    imgUrl: "644187.jpeg",
    rate: "3.8",
    address: "میدان توحید",
    date: ["چهار شنبه", "دوشنبه", "شنبه"],
  },
  {
    id: "8",
    fname: "مهدی",
    lname: "سجادی",
    expert: "قلب و عروق",
    university: "تهران",
    imgUrl: "533913.jpeg",
    rate: "3.7",
    address: "میدان معلم",
    date: ["دو شنبه", "شنبه"],
  },
  {
    id: "9",
    fname: "جلال",
    lname: "تاجیک",
    expert: "روانپزشکی",
    university: "شیراز",
    imgUrl: "297421.jpeg",
    rate: "3.9",
    address: "میدان تجریش",
    date: ["شنبه", "دوشنبه", "پنچشنبه"],
  },
  {
    id: "10",
    fname: "علی اکبر",
    lname: "مهدیانی",
    expert: "بیهوشی",
    university: "تهران",
    imgUrl: "462173.jpeg",
    rate: "4.0",
    address: "تهرانپارس غربی",
    date: ["سه شنبه", "شنبه"],
  },
  {
    id: "11",
    fname: "زهرا",
    lname: "ایوانی",
    expert: "مامایی",
    university: "تربیت مدرس",
    imgUrl: "688564.jpeg",
    rate: "3.6",
    address: "پاتریس لومومبا",
    date: ["یکشنبه", "دوشنبه", "سه شنبه"],
  },
  {
    id: "12",
    fname: "نگار",
    lname: "کوشکی",
    expert: "روانپزشکی",
    university: "تهران",
    imgUrl: "717832.jpeg",
    rate: "4.5",
    address: "گاندی",
    date: ["دو شنبه", "شنبه"],
  },
];

export default data;
